# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



# fastlane/Fastfile
default_platform(:ios)

platform :ios do
  desc "Run unit & UI tests on Simulator (CI-only)"
  lane :ci_test do
	scan(
         scheme: "CICD_iOS",
         clean: true,
         code_coverage: true,
  	 devices: ["iPhone 16 Pro"],   # simple name
         disable_concurrent_testing: true,
         force_quit_simulator: true
        )
  end
end
