name: iOS CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  XCODE_VERSION: "16.4"

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install
      - run: bundle exec pod install
      - run: bundle exec fastlane ci_test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: fastlane-test-report
          path: fastlane/test_output/*
